# Generated by Django 4.1.2 on 2022-10-31 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profile_photos/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
