# Generated by Django 4.1.2 on 2022-10-31 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Urgent', ((1, 'Urgent & Important'), (2, 'Urgent & Not Important'))), ('Not Urgent', ((3, 'Not Urgent & Important'), (4, 'Not Urgent & Not Important')))], default='1', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('create', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
