# Generated by Django 4.1.2 on 2022-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Urgent', (('Urgent & Important', 'Urgent & Important'), ('Urgent & Not Important', 'Urgent & Not Important'))), ('Not Urgent', (('Not Urgent & Important', 'Not Urgent & Important'), ('Not Urgent & Not Important', 'Not Urgent & Not Important')))], default='1', max_length=100),
        ),
    ]
